name: Run TMDb Script

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run Python script
        env:
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
        working-directory: Widgets
        run: |
          python get_tmdb_data.py

      - name: Print current working directory
        run: |
          pwd

      - name: Check if JSON file exists
        run: |
          if [ -f "Widgets/tmdbNowPlaying.json" ]; then
            echo "文件存在：Widgets/tmdbNowPlaying.json"
          else
            echo "错误：文件 Widgets/tmdbNowPlaying.json 不存在！"
            exit 1
          fi

      - name: Add updated JSON file to Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add Widgets/tmdbNowPlaying.json

      - name: Commit changes
        run: |
          git commit -m "自动更新 Widgets/tmdbNowPlaying.json 文件 [skip ci]"
        continue-on-error: true

      - name: Push changes
        run: |
          git push
